module FrontendForFreeParsing

"""
    requirement(::Val{YourLangName}, ::Val{RequiredValueName}) = val
"""
function requirement end

const _MSG_NO_BIN = raw"""
Calling 'fff-pgen' failed.
The required binaries are available at:
    https://github.com/thautwarm/frontend-for-free/releases/

You might need to install or build the binaries (and add them to PATH)
"""

const _MSG_CMD_FAILED = raw"""
It seems that you have installed a wrong version of 'fff-pgen'.
Please check the documentations for compatibility issues, or send a bug report.
"""

function load_fff_impl(caller_module::Module, dirpath::String, sourcepath::String, langName::Symbol)
    jl_path = string(langName) * ".parser.jl" # generated julia source path
    abs_jl_path = joinpath(dirpath, jl_path)
    fff_path = joinpath(dirpath, string(langName) * ".fff")
    if isfile(abs_jl_path)
        try
            cmd = ``
            push!(
                cmd.args,
                "fff-pgen",
                "-in", fff_path,
                "-k", "1",
                "-out", abs_jl_path,
                "-be", "julia",
                "--trace",
                "--noinline"
            )
            run(cmd)
            !isfile(abs_jl_path) && throw(LoadError(sourcepath, ErrorException(_MSG_CMD_FAILED)))
        catch e
            e isa IOError && throw(LoadError(sourcepath, ErrorException(_error_msg)))
            rethrow()
        end
    end
    :(include($jl_path))
end

"""
https://github.com/thautwarm/frontend-for-free
Load code generated by fff-pgen.
"""
macro load_fff!(langName::Symbol)
    sourcepath = string(__source__.file)
    dirpath = string(dirname(abspath()))
    esc(load_fff_impl(__module__, dirpath, sourcepath, langName))
end

end